project:
  type: website

website:
  title: "Epiverce TRACE annual summit"
  navbar:
    background: secondary
    search: true
    pinned: true
    right:
        - text: "Home"
          href: index.qmd
        - text: "Program"
          href: schedule.qmd
        - text: "Pre-summit Training"
          href: pre-training.qmd
        - text: "Travelling to The Gambia"
          href: information.qmd
        - text: "Organising committees"
          href: committees.qmd
        - text: "Contacts"
          href: contact.qmd

  page-footer:
    border: true
    background: light
    left:
        - text: "Contacts"
          href: contact.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

