project:
  type: website

website:
  title: "Epiverse-TRACE Third Annual Summit 2024"
  navbar:
    background: secondary
    search: true
    pinned: true
    right:
        - text: "Programme"
          href: programme.qmd
        - text: "Pre-summit Training"
          href: pre-training.qmd
        - text: "Travel Information"
          href: travel.qmd
        - text: "Committees"
          href: committees.qmd
        - text: "Contact Us"
          href: contact.qmd

  page-footer:
    border: true
    background: light
    left: |
      **Sponsors**:

      [![](./images/LogoDataDotOrg.png){fig-alt="datadotorg" width=60px}](https://data.org/)
      [![](./images/idrc_logo.png){fig-alt="IDRC" width=130px}](https://www.idrc-crdi.ca/en)

    center: |
      **Consortium Members**:

      [![](./images/lshtm-logo.png){fig-alt="LSHTM" width=90px}](https://www.lshtm.ac.uk/)
      [![](./images/UKRI_MRCG_LSHTM_logo.png){fig-alt="MRCG" width=150px}](https://www.lshtm.ac.uk/research/units/mrc-gambia)
      [![](./images/Uniandes.png){fig-alt="uniandes" width=80px}](https://uniandes.edu.co/)
      [![](./images/Javeriana.png){fig-alt="javeriana" width=60px}](https://javeriana.edu.co/)
    right:
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/Epiverse_TRACE
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left

editor: visual

