project:
  type: website

website:
  title: "Epiverce TRACE"
  navbar:
    background: secondary
    search: true
    right:
        - text: "Home"
          href: index.qmd
        - text: "Agenda"
          href: schedule.qmd
        - text: "Pre-summit Training"
          href: pre-training.qmd
        - text: "Travelling to The Gambia"
          href: information.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

