project:
  type: website

website:
  title: "Epiverce TRACE"
  navbar:
    background: secondary
    search: true
    right:
        - text: "Home"
          href: index.qmd
        - text: "Commitees"
          href: committees.qmd
        - text: "Pre-summit Training"
          href: pre-training.qmd
        - text: "Information"
          href: information.qmd
        - text: "Schedule/Program"
          href: schedule.qmd
        - text: "Contact"
          href: contact.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

