project:
  type: website

website:
  title: "Epiverce TRACE annual summit"
  navbar:
    background: secondary
    search: true
    pinned: true
    right:
        - text: "Home"
          href: index.qmd
        - text: "Agenda"
          href: schedule.qmd
        - text: "Pre-summit Training"
          href: pre-training.qmd
        - text: "Travel Information"
          href: information.qmd
        - text: "Committees"
          href: committees.qmd
        - text: "Contact"
          href: contact.qmd

  page-footer:
    border: true
    background: light
    center: |
      [![](./images/UKRI_MRCG_LSHTM_logo.png){fig-alt="MRCG" width=65px}](https://www.lshtm.ac.uk/research/units/mrc-gambia)
      [![](./images/LogoDataDotOrg.png){fig-alt="datadotorg" width=65px}](https://data.org/a)
      [![](./images/logo-andes.png){fig-alt="uniandes" width=65px}](https://uniandes.edu.co/)
      [![](./images/Javeriana.png){fig-alt="javeriana" width=65px}](https://javeriana.edu.co/)
    right:
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/Epiverse_TRACE


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

