## Summit Programme 

```{r}
#| echo: false
#| 
agenda <- data.frame(
  "9 - 11" = c("Opening ceremony and launching of phase 2", "Inclusivity, equity and sustainability day", "", "Designing outbreak analytics course", "Tools for surveillance"),
  "11 - 11:30" = c(rep("Tea break", 2), "", rep("Tea break", 2)),
  "11:30 - 13" = c("Phase 2 implementation planning", "Inclusivity, equity and sustainability day", "", "One health / local outbreaks/ NTDs", "Lessons learnt/Gaps/needs"),
  "13 - 15" = c(rep("lunch", 2), "", rep("lunch", 2)),
  "15 - 17" = c("RSE session", "Inclusivity, equity and sustainability day", "", "RSE session", ""))
rownames(agenda) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
names(agenda) <- c("9 - 11", "11 - 11:30", "11:30 - 13:30", "13:30 - 15", "15 - 17")

agenda |>
  kableExtra::kbl() |>
  kableExtra::kable_paper("striped", font_size = 18, full_width = TRUE) |>
  kableExtra::column_spec(c(3, 5), color = 'white', background = 'black') |>
  kableExtra::row_spec(1:nrow(agenda), extra_css = "padding: 30px") |>
  kableExtra::row_spec(3, background = 'black')
```

## Daily Programme

### Day 1: Epiverse-TRACE phase 2

:::: {.columns}
::: {.column .daily-prog-col width="50%"}

**Opening ceremony**

_Time:_ 09:00-10:00  
_Speakers:_  
_Moderator:_  


_Time:_ 10:00-11:00  
_Speakers:_  
_Moderator:_  


:::
::: {.column .daily-prog-col4 width="50%"}

**Phase 2 implementation planning**

_Time:_ 11:30-12:00  
_Speakers:_  
_Moderator:_  


_Time:_ 12:10-12:50  
_Speakers:_  
_Moderator:_  


:::
::::


:::: {.columns}
::: {.column .daily-prog-col3 width="50%"}

**RSE session**
    
_Time:_ 15:00-17:00  
_Activities:_  
 

:::
::: {.column .daily-prog-col2 width="50%"}

**Dinner**

_Time:_ 19:30-21:00  
_Venue:_  


:::
::::

<!-- ::: {.grid} -->

<!-- ::: {.g-col-6} -->

<!-- ##  <span style="color:#AEC800;">2024-12-26 [09:00 - 10:00]</span> -->

<!-- Opening ceremony -->

<!-- Speakers: -->

<!-- Moderator: -->
<!-- ::: -->

<!-- ::: {.g-col-6} -->

<!-- ## 2024-12-26 [10:00 - 11:00] -->

<!-- launching of phase 2 -->

<!-- Speakers: -->

<!-- Moderator: -->

<!-- ::: -->

<!-- :::   -->



## Sub-topics proposed in preparation meetings

* Sustainability:
    * What will happen to the tools when the funding runs out?
    * How do we keep the project going?
    
* Inclusivity:
    * Where do we locate the global south?

* Building collaboration:
    * Bringing a broader audience to the summit such as the private sector, agencies in the region, and other research groups
    * Establishing alliances with the ones who might find the project useful to them and their organizations.
    
* Training:
    * What have we learned from the training feedback conducted by both the TRACE-Lac and the LSHTM team?
    * How can we adapt the TRACE-LAC training materials to Africa?
