# Travel and Visas

To check whether you need a visa to enter The Gambia, visit the [Visa to The Gambia](https://www.banjulairport.com/en/visa_gambia.php) page.
Other relevant information about entering The Gambia can be found in [this page](https://www.banjulairport.com/en/things_to_know_and_visa_gambia.php#visas).

Attendees (invited or from the TRACE team) living outside The Gambia are encouraged to fill out this [form](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__R90XI1UQ0dZOUhSSUE4Q0NORFQ2SzhHR09STUtRUy4u) to benefit from the support of our logistics committee.

Summit participants requiring a visa letter or any form of travel-related documentation, can send a request to [traveldesk\@mrc.gm](mailto:traveldesk@mrc.gm). Please note that only individuals who have registered for the event will be eligible to receive a visa letter from the organising committee.

# Venue

The summit will take place at the MRCG unit at the LSHTM in Fajara, Banjul. Spanning approximately 100 acres, the unit offers a modern, fully-equipped venue in the heart of Fajara. This convenient location is near various attractions, transport facilities, and accommodations that cater to all preferences.

<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1dV4ybCwRhZEXvbq5XZXWZ2cFmI_0EQ0&amp;ehbc=2E312F&amp;noprof=1" width="100%" height="480">

</iframe>

# Accommodation

To facilitate the participation of attendees, the Epiverse-TRACE 2024 summit local organising committee is pleased to offer a dedicated accommodation option at the [Majula Boutique Hotel](https://www.majulaboutiquehotel.com/). Once your attendance is confirmed, you can book a stay at this modern, newly-built facility. Conveniently located directly opposite and only a few footsteps away from the MRCG unit in Fajara (the summit venue), the hotel features views of this beautiful city on three sides and a rooftop terrace. All rooms are equipped with a private bathroom, air conditioning, and fast, free Wi-Fi.
